backend:
  name: github
  repo: soossandor/abcsportclub-web # IDE ÍRD BE A SAJÁT GITHUB NEVED!
  branch: main
  
# Ide kerülnek majd a cikkekhez feltöltött képek
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "hirek"
    label: "Hírek és Cikkek"
    folder: "src/content/hirek"
    create: true
    summary: "{{title}} - [{{category}}]"
    slug: "{{slug}}"
    fields:
      - {label: "Cím", name: "title", widget: "string"}
      - {label: "Kategória (Hova kerüljön?)", name: "category", widget: "select", options: ["Kezdőlap", "ABC Tenisz Iskola", "Mit kap ebből a gyermek", "Gyakori kérdések", "Hétvégi Sportiskola", "Pickleball Versenyeink", "Versenynaptár", "Senior Tour", "Silver Open", "Golden Serve Tour", "Golden Open", "Wilson Junior Tour", "Mind & Motion Coaching", "Jelentkezés", "Bemutatkozás", "Pickleball és Mini Tenisz", "Galéria", "Kapcsolat", "Táborok", "Raktár", "Törölt", "Készülőben", "Piszkozat", "Jóváhagyásra vár"] }
      - {label: "Dátum", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Rövid összefoglaló", name: "excerpt", widget: "text"}
      - {label: "Borítókép", name: "thumbnail", widget: "image", required: false }
      - {label: "Cikk szövege", name: "body", widget: "markdown"}