backend:
  name: github
  repo: soossandor/abcsportclub-web # IDE ÍRD BE A SAJÁT GITHUB NEVED!
  branch: main
  
# Ide kerülnek majd a cikkekhez feltöltött képek
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "hirek"
    label: "Hírek és Cikkek"
    folder: "src/content/hirek"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Cím", name: "title", widget: "string"}
      - {label: "Kategória (Hova kerüljön?)", name: "category", widget: "select", options: ["Hírek", "ABC Tenisz Iskola", "Hétvégi Sportiskola", "Pickleball Versenyeink", "Coaching", "Táborok"] }
      - {label: "Dátum", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Rövid összefoglaló", name: "excerpt", widget: "text"}
      - {label: "Cikk szövege", name: "body", widget: "markdown"}